import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import Navbar from '../components/navbar'
import PlaceList from '../components/placeList'
import DatePicker from '../components/datePicker'
import { useState } from 'react'
import useSwr from 'swr'
import fetcher from '../lib/fetcher'
import TimeLine from '../components/timeline'

const Home: NextPage = () => {
  const { data: session } = useSession()

  let [daysNum, setDaysNum] = useState(0)

  const places = ['ONE', 'TWO', 'THREE', '4', '5', '6', '7', '8'];

  const { data, error, isLoading } = useSwr('/api/user/' + session?.user.id, fetcher)

  console.log(data);

  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main>
        <div>
          {session && session.user ? (
            <>
              <div>
                <p>Select Days</p>
                <DatePicker getDaysNum={setDaysNum}></DatePicker>
                <TimeLine daysNum={daysNum}></TimeLine>
              </div>
              <PlaceList places={places}></PlaceList>
            </>
          ) : (
            <p>You need to sign in to save your progress</p>
          )}
        </div>
      </main >
    </div >
  )
}

export default Home