import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import Navbar from '../components/navbar'
import PlaceList from '../components/placeList'

const Home: NextPage = () => {
  const { data: session } = useSession()

  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main className={styles.main}>
        <div>
          {session && session.user ? (
            <div className={styles.card}>
              <div className={styles.cardContent}>
                <h2 className="text-3xl">Hello World</h2>
                <p>
                  Insert content here
                </p>
              </div>
              <PlaceList></PlaceList>
            </div>
          ) : (
            <p>You need to sign in to save your progress</p>
          )}
        </div>
      </main>
    </div>
  )
}

export default Home